spring.profiles.include: 'auth'
                                                         show_sql: 보여준다.)
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://54.180.158.97:3306/moggozi
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: c201
    initialization-mode: always
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop          #                                                             show_sql: 보여준다.)
    defer-datasource-initialization: true

logging:                        # logging level은 DEBUG로 설정하겠다.
  level:                        # logging level: All < Debug < Info < Warn < Error < Fatal < Off 가 있다.
    com.JJP: DEBUG        # 불필요한 로그로 인해 비즈니스 로그가 무엇인지를 찾기 힘들기 때문에 레벨을 설정할 수 있다.
    # 이 때, Debug 아래의 Info, Warn, Error, Fatal 까지의 로그가 찍힌다, Off는 로그를 보지 않겠다는 것이다.

