jwt:
  header: Authorization
  secret: MjIwNy1maXJzdC1wcm9qZWN0LWp3dC10b2tlbi1wcmVzZW50ZWQtYnktbW9nZ296aS1hbmQtc3VwcG9ydGVkLWJ5LXNzYWZ5Cg==
  cookieName: moggozi
  accessExpirationInMs: 36000000        # Access 토큰 만료 시간(ms) = 5시간
  refreshExpirationInMs: 86400000       # Refresh 토큰 만료 시간(ms) = 1일 (24시간)

#spring:
#  security:
#    oauth2.client:
#        registration:
#          google:
#            clientId: 948844328868-cos0sa2t47h5qva1glcsoijkt2690g35.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - profile
#              - email



